# For manual testing, requires IntelliJ IDEA Ultimate and a running instance of the application
###
POST http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "APPLES",
  "quantity": 5
}

###
POST http://localhost:8080/api/register
Content-Type: application/x-www-form-urlencoded

username=john&password=password
